### ISSUE TITLE
Code not Running

### ISSUE THREAD

**Issue by asfaarahmed** [manekinekko/angular2-speech-engine#1]
After clone your repo and start project it throw errors.. Another Thing Kindly add something in readme.md for better understanding.. 
![screenshot 214](https://cloud.githubusercontent.com/assets/19251229/15159032/f130892c-170b-11e6-96c2-d653bdc5ac77.png)

**Comment by manekinekko** [comment]
Hi @asfaarahmed If your command doesn't work, it is simply because in the `package.json` I have no `start` script. This lib is meant to be imported into your project, not run as a standalone lib.

BTW, this module is still WIP, hence the absence of the readme. In the meantime, you can have a look a this app which uses this speech engine:
- https://github.com/manekinekko/gif-finder/blob/master/package.json#L28
- https://github.com/manekinekko/gif-finder/blob/master/src/client/app/speech-to-text/speech-to-text.ts#L4
